version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.1-stretch
    steps:
      - checkout

      - run:
          name: Install Python Environment
          command: |
            sudo apt-get update
            sudo apt-get install python3-pip build-essential libssl-dev python3-dev -y
            sudo python3 -m pip install --upgrade pip setuptools
            sudo python3 -m pip install --progress-bar off --requirement requirements-for-testing.txt
      - run: make test
